title: Neural News Recommendation - Foundations, Challenges, and Future Directions
description: Tutorial on neural news recommendation
show_downloads: false
theme: jekyll-theme-cayman

conference_name: "Tutorial on Neural News Recommendation: Foundations, Challenges, and Future Directions"
conference_www: "Venue & Date: TBD"
conference_venue: ""
conference_time: ""
conference_intro: ""

github:
  zip_url: http://www.google.com

collections:
  organizers:
    output: true
